frame-support: make `#[stored]` work in crates without a direct `derive-where` dependency' (#13421)
## The problem
Today `#[frame_support::stored]` on a generic type fails in any crate
that depends on `frame-support` but not directly on `derive-where`:

```
error[E0433]: cannot find `derive_where` in the crate root
error: cannot find attribute `derive_where` in this scope
```

The macro emits `#[frame_support::derive_where::derive_where(..)]`, but
`derive_where` itself expands to `::derive_where::...` paths unless
given a `crate` option.
The existing tests did not catch this because `frame-support-test`
depends on `derive-where` directly e.g.

[`test_stored_struct_implements_required_traits`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/test/tests/stored.rs#L72),
[`test_stored_enum_implements_required_traits`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/test/tests/stored.rs#L78),
[`test_derive_where_not_needed_storable`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/test/tests/stored.rs#L86),
[`test_no_generics_storable`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/test/tests/stored.rs#L94),
[`no_skip_type_params`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/test/tests/stored.rs#L100).

## Solution

`#[stored]` already calls `derive_where` through the `frame-support`
re-export. The problem is the code `derive_where` generates: it roots
its helper paths at `::derive_where` unless told otherwise with a `crate
= ...` option.

Before:
```rust
// emitted by #[stored]
#[frame_support::derive_where::derive_where(Clone, Eq, PartialEq, Debug; ...)]
struct Foo<T, S: Get<u32>> { items: BoundedVec<T, S> }

// then emitted by derive_where
#[derive(::derive_where::DeriveWhere)]      // needs a direct `derive-where` dependency
#[::derive_where::derive_where_visited]
```

After:
```rust
// emitted by #[stored]
#[frame_support::derive_where::derive_where(Clone, Eq, PartialEq, Debug; ...)]
#[derive_where(crate = frame_support::derive_where)]
struct Foo<T, S: Get<u32>> { items: BoundedVec<T, S> }

// then emitted by derive_where
#[derive(frame_support::derive_where::DeriveWhere)]      // resolves through the re-export
#[frame_support::derive_where::derive_where_visited]
```

The `crate` attribute must follow the `derive_where` call, since an
attribute macro only sees the attributes below it.

---------

Co-authored-by: Bastian Köcher <git@kchr.de>